info:
  app:
    name: streaming-info-service
    description: Shows information of where and how you can stream audio and videos

server:
  port: 8014

spring:
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost/test
      username: root
      password: dbpass