info:
  app:
    name: streaming-info-service
    description: Shows information of where and how you can stream audio and videos

endpoints:
  restart:
    enabled: true
  refresh:
    enabled: true

server:
  port: 8045

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/streaming
        username: dbuser
        password: dbpass

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ni:
  servers: localhost:7654

---
spring:
    profiles: docker

server:
    port: 8080

spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysql/test
        username: root
        password: dbpass

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

ni:
  servers: niserver:7654